/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.amf.registration.monitor.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the UserEvents service. Represents a row in the &quot;Monitor_UserEvents&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.amf.registration.monitor.model.impl.UserEventsModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.amf.registration.monitor.model.impl.UserEventsImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see UserEvents
 * @generated
 */
@ProviderType
public interface UserEventsModel
	extends BaseModel<UserEvents>, GroupedModel, ShardedModel,
			StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a user events model instance should use the {@link UserEvents} interface instead.
	 */

	/**
	 * Returns the primary key of this user events.
	 *
	 * @return the primary key of this user events
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this user events.
	 *
	 * @param primaryKey the primary key of this user events
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this user events.
	 *
	 * @return the uuid of this user events
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this user events.
	 *
	 * @param uuid the uuid of this user events
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the user event ID of this user events.
	 *
	 * @return the user event ID of this user events
	 */
	public long getUserEventId();

	/**
	 * Sets the user event ID of this user events.
	 *
	 * @param userEventId the user event ID of this user events
	 */
	public void setUserEventId(long userEventId);

	/**
	 * Returns the group ID of this user events.
	 *
	 * @return the group ID of this user events
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this user events.
	 *
	 * @param groupId the group ID of this user events
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this user events.
	 *
	 * @return the company ID of this user events
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this user events.
	 *
	 * @param companyId the company ID of this user events
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this user events.
	 *
	 * @return the user ID of this user events
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this user events.
	 *
	 * @param userId the user ID of this user events
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this user events.
	 *
	 * @return the user uuid of this user events
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this user events.
	 *
	 * @param userUuid the user uuid of this user events
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this user events.
	 *
	 * @return the user name of this user events
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this user events.
	 *
	 * @param userName the user name of this user events
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this user events.
	 *
	 * @return the create date of this user events
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this user events.
	 *
	 * @param createDate the create date of this user events
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this user events.
	 *
	 * @return the modified date of this user events
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this user events.
	 *
	 * @param modifiedDate the modified date of this user events
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the ip address of this user events.
	 *
	 * @return the ip address of this user events
	 */
	@AutoEscape
	public String getIpAddress();

	/**
	 * Sets the ip address of this user events.
	 *
	 * @param ipAddress the ip address of this user events
	 */
	public void setIpAddress(String ipAddress);

	/**
	 * Returns the type of this user events.
	 *
	 * @return the type of this user events
	 */
	@AutoEscape
	public String getType();

	/**
	 * Sets the type of this user events.
	 *
	 * @param type the type of this user events
	 */
	public void setType(String type);

	/**
	 * Returns the screen name of this user events.
	 *
	 * @return the screen name of this user events
	 */
	@AutoEscape
	public String getScreenName();

	/**
	 * Sets the screen name of this user events.
	 *
	 * @param screenName the screen name of this user events
	 */
	public void setScreenName(String screenName);

}