/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.amf.registration.search.model;

import com.amf.registration.search.service.persistence.UserAddressPK;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ShardedModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the UserAddress service. Represents a row in the &quot;RegistrationSearch_UserAddress&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.amf.registration.search.model.impl.UserAddressModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.amf.registration.search.model.impl.UserAddressImpl</code>.
 * </p>
 *
 * @author Brian Heise
 * @see UserAddress
 * @generated
 */
@ProviderType
public interface UserAddressModel extends BaseModel<UserAddress>, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a user address model instance should use the {@link UserAddress} interface instead.
	 */

	/**
	 * Returns the primary key of this user address.
	 *
	 * @return the primary key of this user address
	 */
	public UserAddressPK getPrimaryKey();

	/**
	 * Sets the primary key of this user address.
	 *
	 * @param primaryKey the primary key of this user address
	 */
	public void setPrimaryKey(UserAddressPK primaryKey);

	/**
	 * Returns the user ID of this user address.
	 *
	 * @return the user ID of this user address
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this user address.
	 *
	 * @param userId the user ID of this user address
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this user address.
	 *
	 * @return the user uuid of this user address
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this user address.
	 *
	 * @param userUuid the user uuid of this user address
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the company ID of this user address.
	 *
	 * @return the company ID of this user address
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this user address.
	 *
	 * @param companyId the company ID of this user address
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the name of this user address.
	 *
	 * @return the name of this user address
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this user address.
	 *
	 * @param name the name of this user address
	 */
	public void setName(String name);

	/**
	 * Returns the screen name of this user address.
	 *
	 * @return the screen name of this user address
	 */
	@AutoEscape
	public String getScreenName();

	/**
	 * Sets the screen name of this user address.
	 *
	 * @param screenName the screen name of this user address
	 */
	public void setScreenName(String screenName);

	/**
	 * Returns the email address of this user address.
	 *
	 * @return the email address of this user address
	 */
	@AutoEscape
	public String getEmailAddress();

	/**
	 * Sets the email address of this user address.
	 *
	 * @param emailAddress the email address of this user address
	 */
	public void setEmailAddress(String emailAddress);

	/**
	 * Returns the zip of this user address.
	 *
	 * @return the zip of this user address
	 */
	@AutoEscape
	public String getZip();

	/**
	 * Sets the zip of this user address.
	 *
	 * @param zip the zip of this user address
	 */
	public void setZip(String zip);

}