/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.amf.registration.profile.model.impl;

import com.amf.registration.profile.model.GeneralProfile;
import com.amf.registration.profile.model.GeneralProfileModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the GeneralProfile service. Represents a row in the &quot;UserProfile_GeneralProfile&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>GeneralProfileModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link GeneralProfileImpl}.
 * </p>
 *
 * @author Brian Heise
 * @see GeneralProfileImpl
 * @generated
 */
public class GeneralProfileModelImpl
	extends BaseModelImpl<GeneralProfile> implements GeneralProfileModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a general profile model instance should use the <code>GeneralProfile</code> interface instead.
	 */
	public static final String TABLE_NAME = "UserProfile_GeneralProfile";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"generalProfileId", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"aboutMe", Types.VARCHAR}, {"favoriteQuotes", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("generalProfileId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("aboutMe", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("favoriteQuotes", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table UserProfile_GeneralProfile (uuid_ VARCHAR(75) null,generalProfileId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,aboutMe VARCHAR(75) null,favoriteQuotes VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP =
		"drop table UserProfile_GeneralProfile";

	public static final String ORDER_BY_JPQL =
		" ORDER BY generalProfile.userName ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY UserProfile_GeneralProfile.userName ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long USERID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long USERNAME_COLUMN_BITMASK = 16L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public GeneralProfileModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _generalProfileId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setGeneralProfileId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _generalProfileId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return GeneralProfile.class;
	}

	@Override
	public String getModelClassName() {
		return GeneralProfile.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<GeneralProfile, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<GeneralProfile, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<GeneralProfile, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((GeneralProfile)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<GeneralProfile, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<GeneralProfile, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(GeneralProfile)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<GeneralProfile, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<GeneralProfile, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, GeneralProfile>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			GeneralProfile.class.getClassLoader(), GeneralProfile.class,
			ModelWrapper.class);

		try {
			Constructor<GeneralProfile> constructor =
				(Constructor<GeneralProfile>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<GeneralProfile, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<GeneralProfile, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<GeneralProfile, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<GeneralProfile, Object>>();
		Map<String, BiConsumer<GeneralProfile, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<GeneralProfile, ?>>();

		attributeGetterFunctions.put("uuid", GeneralProfile::getUuid);
		attributeSetterBiConsumers.put(
			"uuid",
			(BiConsumer<GeneralProfile, String>)GeneralProfile::setUuid);
		attributeGetterFunctions.put(
			"generalProfileId", GeneralProfile::getGeneralProfileId);
		attributeSetterBiConsumers.put(
			"generalProfileId",
			(BiConsumer<GeneralProfile, Long>)
				GeneralProfile::setGeneralProfileId);
		attributeGetterFunctions.put("groupId", GeneralProfile::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId",
			(BiConsumer<GeneralProfile, Long>)GeneralProfile::setGroupId);
		attributeGetterFunctions.put("companyId", GeneralProfile::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<GeneralProfile, Long>)GeneralProfile::setCompanyId);
		attributeGetterFunctions.put("userId", GeneralProfile::getUserId);
		attributeSetterBiConsumers.put(
			"userId",
			(BiConsumer<GeneralProfile, Long>)GeneralProfile::setUserId);
		attributeGetterFunctions.put("userName", GeneralProfile::getUserName);
		attributeSetterBiConsumers.put(
			"userName",
			(BiConsumer<GeneralProfile, String>)GeneralProfile::setUserName);
		attributeGetterFunctions.put(
			"createDate", GeneralProfile::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<GeneralProfile, Date>)GeneralProfile::setCreateDate);
		attributeGetterFunctions.put(
			"modifiedDate", GeneralProfile::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<GeneralProfile, Date>)GeneralProfile::setModifiedDate);
		attributeGetterFunctions.put("aboutMe", GeneralProfile::getAboutMe);
		attributeSetterBiConsumers.put(
			"aboutMe",
			(BiConsumer<GeneralProfile, String>)GeneralProfile::setAboutMe);
		attributeGetterFunctions.put(
			"favoriteQuotes", GeneralProfile::getFavoriteQuotes);
		attributeSetterBiConsumers.put(
			"favoriteQuotes",
			(BiConsumer<GeneralProfile, String>)
				GeneralProfile::setFavoriteQuotes);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@Override
	public long getGeneralProfileId() {
		return _generalProfileId;
	}

	@Override
	public void setGeneralProfileId(long generalProfileId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_generalProfileId = generalProfileId;
	}

	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("groupId"));
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalUserId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("userId"));
	}

	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@Override
	public String getAboutMe() {
		if (_aboutMe == null) {
			return "";
		}
		else {
			return _aboutMe;
		}
	}

	@Override
	public void setAboutMe(String aboutMe) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_aboutMe = aboutMe;
	}

	@Override
	public String getFavoriteQuotes() {
		if (_favoriteQuotes == null) {
			return "";
		}
		else {
			return _favoriteQuotes;
		}
	}

	@Override
	public void setFavoriteQuotes(String favoriteQuotes) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_favoriteQuotes = favoriteQuotes;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(GeneralProfile.class.getName()));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), GeneralProfile.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public GeneralProfile toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, GeneralProfile>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		GeneralProfileImpl generalProfileImpl = new GeneralProfileImpl();

		generalProfileImpl.setUuid(getUuid());
		generalProfileImpl.setGeneralProfileId(getGeneralProfileId());
		generalProfileImpl.setGroupId(getGroupId());
		generalProfileImpl.setCompanyId(getCompanyId());
		generalProfileImpl.setUserId(getUserId());
		generalProfileImpl.setUserName(getUserName());
		generalProfileImpl.setCreateDate(getCreateDate());
		generalProfileImpl.setModifiedDate(getModifiedDate());
		generalProfileImpl.setAboutMe(getAboutMe());
		generalProfileImpl.setFavoriteQuotes(getFavoriteQuotes());

		generalProfileImpl.resetOriginalValues();

		return generalProfileImpl;
	}

	@Override
	public int compareTo(GeneralProfile generalProfile) {
		int value = 0;

		value = getUserName().compareTo(generalProfile.getUserName());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof GeneralProfile)) {
			return false;
		}

		GeneralProfile generalProfile = (GeneralProfile)object;

		long primaryKey = generalProfile.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<GeneralProfile> toCacheModel() {
		GeneralProfileCacheModel generalProfileCacheModel =
			new GeneralProfileCacheModel();

		generalProfileCacheModel.uuid = getUuid();

		String uuid = generalProfileCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			generalProfileCacheModel.uuid = null;
		}

		generalProfileCacheModel.generalProfileId = getGeneralProfileId();

		generalProfileCacheModel.groupId = getGroupId();

		generalProfileCacheModel.companyId = getCompanyId();

		generalProfileCacheModel.userId = getUserId();

		generalProfileCacheModel.userName = getUserName();

		String userName = generalProfileCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			generalProfileCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			generalProfileCacheModel.createDate = createDate.getTime();
		}
		else {
			generalProfileCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			generalProfileCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			generalProfileCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		generalProfileCacheModel.aboutMe = getAboutMe();

		String aboutMe = generalProfileCacheModel.aboutMe;

		if ((aboutMe != null) && (aboutMe.length() == 0)) {
			generalProfileCacheModel.aboutMe = null;
		}

		generalProfileCacheModel.favoriteQuotes = getFavoriteQuotes();

		String favoriteQuotes = generalProfileCacheModel.favoriteQuotes;

		if ((favoriteQuotes != null) && (favoriteQuotes.length() == 0)) {
			generalProfileCacheModel.favoriteQuotes = null;
		}

		return generalProfileCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<GeneralProfile, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(4 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<GeneralProfile, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<GeneralProfile, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((GeneralProfile)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<GeneralProfile, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<GeneralProfile, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<GeneralProfile, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((GeneralProfile)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, GeneralProfile>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private String _uuid;
	private long _generalProfileId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _aboutMe;
	private String _favoriteQuotes;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<GeneralProfile, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((GeneralProfile)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("generalProfileId", _generalProfileId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("aboutMe", _aboutMe);
		_columnOriginalValues.put("favoriteQuotes", _favoriteQuotes);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("generalProfileId", 2L);

		columnBitmasks.put("groupId", 4L);

		columnBitmasks.put("companyId", 8L);

		columnBitmasks.put("userId", 16L);

		columnBitmasks.put("userName", 32L);

		columnBitmasks.put("createDate", 64L);

		columnBitmasks.put("modifiedDate", 128L);

		columnBitmasks.put("aboutMe", 256L);

		columnBitmasks.put("favoriteQuotes", 512L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private GeneralProfile _escapedModel;

}