/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.amf.registration.profile.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Genre service. Represents a row in the &quot;UserProfile_Genre&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.amf.registration.profile.model.impl.GenreModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.amf.registration.profile.model.impl.GenreImpl</code>.
 * </p>
 *
 * @author Brian Heise
 * @see Genre
 * @generated
 */
@ProviderType
public interface GenreModel extends BaseModel<Genre> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a genre model instance should use the {@link Genre} interface instead.
	 */

	/**
	 * Returns the primary key of this genre.
	 *
	 * @return the primary key of this genre
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this genre.
	 *
	 * @param primaryKey the primary key of this genre
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this genre.
	 *
	 * @return the uuid of this genre
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this genre.
	 *
	 * @param uuid the uuid of this genre
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the genre ID of this genre.
	 *
	 * @return the genre ID of this genre
	 */
	public long getGenreId();

	/**
	 * Sets the genre ID of this genre.
	 *
	 * @param genreId the genre ID of this genre
	 */
	public void setGenreId(long genreId);

	/**
	 * Returns the genre name of this genre.
	 *
	 * @return the genre name of this genre
	 */
	@AutoEscape
	public String getGenreName();

	/**
	 * Sets the genre name of this genre.
	 *
	 * @param genreName the genre name of this genre
	 */
	public void setGenreName(String genreName);

}