/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.amf.registration.profile.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the MovieInterest service. Represents a row in the &quot;UserProfile_MovieInterest&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.amf.registration.profile.model.impl.MovieInterestModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.amf.registration.profile.model.impl.MovieInterestImpl</code>.
 * </p>
 *
 * @author Brian Heise
 * @see MovieInterest
 * @generated
 */
@ProviderType
public interface MovieInterestModel
	extends BaseModel<MovieInterest>, GroupedModel, ShardedModel,
			StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a movie interest model instance should use the {@link MovieInterest} interface instead.
	 */

	/**
	 * Returns the primary key of this movie interest.
	 *
	 * @return the primary key of this movie interest
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this movie interest.
	 *
	 * @param primaryKey the primary key of this movie interest
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this movie interest.
	 *
	 * @return the uuid of this movie interest
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this movie interest.
	 *
	 * @param uuid the uuid of this movie interest
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the movie interest ID of this movie interest.
	 *
	 * @return the movie interest ID of this movie interest
	 */
	public long getMovieInterestId();

	/**
	 * Sets the movie interest ID of this movie interest.
	 *
	 * @param movieInterestId the movie interest ID of this movie interest
	 */
	public void setMovieInterestId(long movieInterestId);

	/**
	 * Returns the group ID of this movie interest.
	 *
	 * @return the group ID of this movie interest
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this movie interest.
	 *
	 * @param groupId the group ID of this movie interest
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this movie interest.
	 *
	 * @return the company ID of this movie interest
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this movie interest.
	 *
	 * @param companyId the company ID of this movie interest
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this movie interest.
	 *
	 * @return the user ID of this movie interest
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this movie interest.
	 *
	 * @param userId the user ID of this movie interest
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this movie interest.
	 *
	 * @return the user uuid of this movie interest
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this movie interest.
	 *
	 * @param userUuid the user uuid of this movie interest
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this movie interest.
	 *
	 * @return the user name of this movie interest
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this movie interest.
	 *
	 * @param userName the user name of this movie interest
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this movie interest.
	 *
	 * @return the create date of this movie interest
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this movie interest.
	 *
	 * @param createDate the create date of this movie interest
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this movie interest.
	 *
	 * @return the modified date of this movie interest
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this movie interest.
	 *
	 * @param modifiedDate the modified date of this movie interest
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the favorite genre ID of this movie interest.
	 *
	 * @return the favorite genre ID of this movie interest
	 */
	public long getFavoriteGenreId();

	/**
	 * Sets the favorite genre ID of this movie interest.
	 *
	 * @param favoriteGenreId the favorite genre ID of this movie interest
	 */
	public void setFavoriteGenreId(long favoriteGenreId);

	/**
	 * Returns the favorite movie of this movie interest.
	 *
	 * @return the favorite movie of this movie interest
	 */
	@AutoEscape
	public String getFavoriteMovie();

	/**
	 * Sets the favorite movie of this movie interest.
	 *
	 * @param favoriteMovie the favorite movie of this movie interest
	 */
	public void setFavoriteMovie(String favoriteMovie);

	/**
	 * Returns the least fav movie of this movie interest.
	 *
	 * @return the least fav movie of this movie interest
	 */
	@AutoEscape
	public String getLeastFavMovie();

	/**
	 * Sets the least fav movie of this movie interest.
	 *
	 * @param leastFavMovie the least fav movie of this movie interest
	 */
	public void setLeastFavMovie(String leastFavMovie);

	/**
	 * Returns the favorite actor of this movie interest.
	 *
	 * @return the favorite actor of this movie interest
	 */
	@AutoEscape
	public String getFavoriteActor();

	/**
	 * Sets the favorite actor of this movie interest.
	 *
	 * @param favoriteActor the favorite actor of this movie interest
	 */
	public void setFavoriteActor(String favoriteActor);

}